/* eslint-disable @typescript-eslint/no-unsafe-assignment */
/* eslint-disable @typescript-eslint/no-unsafe-argument */
/* eslint-disable @typescript-eslint/no-unsafe-member-access */
/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable @typescript-eslint/no-unsafe-call */

import Chat from "@/components/Chat";
import { ThemeProvider } from "@/components/ThemeProvider";

import Sidebar from "@/components/Sidebar";
import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const Home: NextPage = ({ datas }: any) => {
  const [selectedModel, setSelectedModel] = useState<string>("gpt-3.5-turbo");
  const [models, setModels] = useState<any[] | null>(null);
  useEffect(() => {
    const ids = datas?.data?.map((x: { id: string }) => x.id);
    setModels(ids);
  }, [datas?.data]);

  return (
    <>
      <Head>
        <title>ChatGPT-clone</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen w-full sm:flex-col sm:overflow-y-hidden md:relative md:flex-row">
        <ThemeProvider>
          <Sidebar
            data={models}
            models={selectedModel}
            selected={setSelectedModel}
          />
          <Chat />
        </ThemeProvider>
      </main>
    </>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async () => {
  const res = await fetch(
    `https://api.openai.com/v1/models`,

    {
      method: "GET",
      // eslint-disable-next-line @typescript-eslint/restrict-template-expressions
      headers: { Authorization: `Bearer ${process.env.OPENAI_API_KEY}` },
    }
  );

  // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
  const datas = await res.json();
  return {
    // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
    props: { datas }, // will be passed to the page component as props
  };
};
