import Chat from "@/components/Chat";
import Sidebar from "@/components/Sidebar";
import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>ChatGPT-clone</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-row relative w-full h-full">
        <Sidebar />
        <Chat />
      </main>
    </>
  );
};

export default Home;
